import{a as S,S as M,i as c}from"./assets/vendor-06b1bbdf.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function h(t,o){const i="https://pixabay.com/api/";return(await S.get(i,{params:{key:"43104791-fccc42375971f64c47e678deb",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}})).data}const v=document.querySelector(".gallery"),P=new M(".gallery a",{captionsData:"alt"});async function u(t){const o=t.map(({largeImageURL:i,webformatURL:n,tags:e,likes:r,views:a,comments:q,downloads:w})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${i}">
        <img class="photo" src="${n}" alt="${e}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${a}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${q}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${w}</p></li>
        </ul>
        </li>`).join("");v.insertAdjacentHTML("beforeend",o),P.refresh()}const m=document.querySelector(".gallery"),R=document.querySelector("form"),g=document.querySelector(".loader"),d=document.querySelector(".btnMore");let s=1,l,p,$=15;function y(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}R.addEventListener("submit",E);async function E(t){if(t.preventDefault(),m.innerHTML="",s=1,l=t.target.elements.search.value.trim(),y(),l===""){c.warning({color:"yellow",message:"Please fill in the field for search!",position:"topRight"});return}try{const o=await h(l,s);o.hits.length===0&&c.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",position:"topRight"}),p=Math.ceil(o.totalHits/$),o.hits.length<15&&f(),u(o.hits),t.target.reset()}catch(o){console.log(o),c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}b(),L(),t.target.reset()}function I(){d.classList.remove("is-hidden")}function f(){d.classList.add("is-hidden")}function b(){s>=p?f():I()}function O(){const t=m.firstElementChild.getBoundingClientRect().height;scrollBy({top:t,behavior:"smooth"})}d.addEventListener("click",B);async function B(){s+=1,y();try{const t=await h(l,s);u(t.hits),s>=p&&(f(),c.info({title:"Info:",message:"You have reached the end of the list",position:"topRight"}))}catch(t){console.log(t),c.info({title:"Info:",message:"You have reached the end of the list",position:"topRight"})}O(),b(),L()}
//# sourceMappingURL=commonHelpers.js.map
